services:
  db:
    image: postgres:15
    container_name: puzzlemapp-db
    restart: always
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: puzlmapp-backend
    restart: always
    ports:
      - "127.0.0.1:${PORT}:3000"
    volumes:
      - ./server:/app/server
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: nginx:stable
    container_name: puzlmapp-frontend
    restart: always
    ports:
      # - "127.0.0.1:5173:5173" # Vite dev server runs on port 5173
      - "127.0.0.1:80:80"     # Nginx runs on port 80
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      
    healthcheck:
      # test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"] #vite dev server
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]   #nginx
      interval: 10s
      timeout: 5s
      retries: 3
    command: npm run dev # Run Vite in development mode
    working_dir: /app/client


volumes:
  db_data:
