services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "127.0.0.1:5173:5173" # Vite dev server
    volumes:
      - ./client:/app/client # Mount client folder for live updates
      - /app/client/node_modules # Exclude node_modules
    working_dir: /app/client
    command: npm run dev -- --host # Ensure Vite binds to 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
