# Use Node.js LTS version
FROM node:lts

# Set working directory
WORKDIR /app/client

# Copy package files and install dependencies
COPY ./client/package*.json ./
RUN npm install --legacy-peer-deps

# Copy the rest of the client files
COPY ./client ./

# Expose Vite's dev server port
EXPOSE 5173

# Command to run Vite in dev mode
CMD ["npm", "run", "dev"]
